name: places
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.1
  cupertino_icons: ^1.0.2
  surf_lint_rules: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - assset: resources/fonts/Roboto/Roboto-Black.ttf
        - asset: resources/fonts/Roboto/Roboto-BlackItalic.ttf
          style: italic
        - assset: resources/fonts/Roboto/Roboto-Bold.ttf
        - asset: resources/fonts/Roboto/Roboto-BoldItalic.ttf
          style: italic
        - asset: resources/fonts/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: resources/fonts/Roboto/Roboto-Light.ttf
        - asset: resources/fonts/Roboto/Roboto-LightItalic.ttf
          style: italic
        - asset: resources/fonts/Roboto/Roboto-Medium.ttf
        - asset: resources/fonts/Roboto/Roboto-MediumItalic.ttf
          style: italic
        - asset: resources/fonts/Roboto/Roboto-Regular.ttf
        - asset: resources/fonts/Roboto/Roboto-Thin.ttf
        - asset: resources/fonts/Roboto/Roboto-ThinItalic.ttf
          style: italic
